-- ROADMAP 152：角色屬性加點系統。
-- 向後相容：ADD COLUMN IF NOT EXISTS，舊資料列讀為 0（DEFAULT 0）。
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS stat_unspent   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_hp        INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_attack    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_speed     INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_atk_speed INTEGER NOT NULL DEFAULT 0;
