-- ROADMAP 153：技能使用型熟練度系統。
-- 向後相容：ADD COLUMN IF NOT EXISTS，舊資料列讀為 0（DEFAULT 0）。
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS skill_use_warcry    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skill_use_bounty    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skill_use_precision INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skill_use_gale      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skill_use_haggle    INTEGER NOT NULL DEFAULT 0;
